version: "3.2"

services:
  test-server:
    image: itzg/minecraft-server
    ports:
      - "25566:25566"
    environment:
      # Server
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.18.1"
      MEMORY: 2G

      # Server Properties
      SEED: 6735220132446817564
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 16

      OPS: Ricky12Awesome

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./server:/data